name: Java CI with Gradle Wrapper

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle Wrapper
      run: ./gradlew build
    - name: Upload artifcat
      uses: actions/upload-artifact@v1
      with:
        name: intellij-kubernetes
        path: build/distributions
